//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopDeLoop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Iterative")]
        public string SolverType {
            get {
                return ((string)(this["SolverType"]));
            }
            set {
                this["SolverType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SimpleSolverDepth {
            get {
                return ((int)(this["SimpleSolverDepth"]));
            }
            set {
                this["SimpleSolverDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AutoMove {
            get {
                return ((int)(this["AutoMove"]));
            }
            set {
                this["AutoMove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowObviousFalseMoves {
            get {
                return ((bool)(this["AllowObviousFalseMoves"]));
            }
            set {
                this["AllowObviousFalseMoves"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConsiderMultipleLoops {
            get {
                return ((bool)(this["ConsiderMultipleLoops"]));
            }
            set {
                this["ConsiderMultipleLoops"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseICinAuto {
            get {
                return ((bool)(this["UseICinAuto"]));
            }
            set {
                this["UseICinAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseICinSolver {
            get {
                return ((bool)(this["UseICinSolver"]));
            }
            set {
                this["UseICinSolver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStart {
            get {
                return ((bool)(this["AutoStart"]));
            }
            set {
                this["AutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 9.75pt")]
        public global::System.Drawing.Font BoardFont {
            get {
                return ((global::System.Drawing.Font)(this["BoardFont"]));
            }
            set {
                this["BoardFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.0.0")]
        public string LastVersionSave {
            get {
                return ((string)(this["LastVersionSave"]));
            }
            set {
                this["LastVersionSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VisualSolve {
            get {
                return ((bool)(this["VisualSolve"]));
            }
            set {
                this["VisualSolve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowColors {
            get {
                return ((bool)(this["ShowColors"]));
            }
            set {
                this["ShowColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConsiderMultipleLoopsInAuto {
            get {
                return ((bool)(this["ConsiderMultipleLoopsInAuto"]));
            }
            set {
                this["ConsiderMultipleLoopsInAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double GenerateLengthFraction {
            get {
                return ((double)(this["GenerateLengthFraction"]));
            }
            set {
                this["GenerateLengthFraction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G,SI,S")]
        public string RatingCodes {
            get {
                return ((string)(this["RatingCodes"]));
            }
            set {
                this["RatingCodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseColoringInSolver {
            get {
                return ((bool)(this["UseColoringInSolver"]));
            }
            set {
                this["UseColoringInSolver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseColoringInAuto {
            get {
                return ((bool)(this["UseColoringInAuto"]));
            }
            set {
                this["UseColoringInAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClock {
            get {
                return ((bool)(this["ShowClock"]));
            }
            set {
                this["ShowClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SimpleSolverRecurseDepth {
            get {
                return ((int)(this["SimpleSolverRecurseDepth"]));
            }
            set {
                this["SimpleSolverRecurseDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCellColoringInSolver {
            get {
                return ((bool)(this["UseCellColoringInSolver"]));
            }
            set {
                this["UseCellColoringInSolver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCellColors {
            get {
                return ((bool)(this["ShowCellColors"]));
            }
            set {
                this["ShowCellColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCellColorsAdvanced {
            get {
                return ((bool)(this["ShowCellColorsAdvanced"]));
            }
            set {
                this["ShowCellColorsAdvanced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCellColoringInAuto {
            get {
                return ((bool)(this["UseCellColoringInAuto"]));
            }
            set {
                this["UseCellColoringInAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDerivedColoringInSolver {
            get {
                return ((bool)(this["UseDerivedColoringInSolver"]));
            }
            set {
                this["UseDerivedColoringInSolver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseMergeInSolver {
            get {
                return ((bool)(this["UseMergeInSolver"]));
            }
            set {
                this["UseMergeInSolver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseEdgeRestrictsInSolver {
            get {
                return ((bool)(this["UseEdgeRestrictsInSolver"]));
            }
            set {
                this["UseEdgeRestrictsInSolver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseEdgeRestrictsInAuto {
            get {
                return ((bool)(this["UseEdgeRestrictsInAuto"]));
            }
            set {
                this["UseEdgeRestrictsInAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double GenerateBoringFraction {
            get {
                return ((double)(this["GenerateBoringFraction"]));
            }
            set {
                this["GenerateBoringFraction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCellPairsInAuto {
            get {
                return ((bool)(this["UseCellPairsInAuto"]));
            }
            set {
                this["UseCellPairsInAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCellPairsInSolver {
            get {
                return ((bool)(this["UseCellPairsInSolver"]));
            }
            set {
                this["UseCellPairsInSolver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCellPairsTopLevelInSolver {
            get {
                return ((bool)(this["UseCellPairsTopLevelInSolver"]));
            }
            set {
                this["UseCellPairsTopLevelInSolver"] = value;
            }
        }
    }
}
